spring:
  application:
    name: diagram-api
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://diagram-db-instance.c7yaceqg6baa.us-east-1.rds.amazonaws.com:5432/diagram_db}
    username: ${DB_USERNAME:diagram_api}
    password: ${DB_PASSWORD:diagramdbpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          type_blob: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    aws:
      region:
        static: us-east-1
      sqs:
        queue-diagram.process: ${SQS_PROCESS_URL:https://sqs.us-east-1.amazonaws.com/481824691194/diagram-process}
        queue-diagram.status.update: ${SQS_STATUS_URL:https://sqs.us-east-1.amazonaws.com/481824691194/diagram-status-update}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  session-token: ${AWS_SESSION_TOKEN}
